apiVersion: v1
kind: Namespace
metadata:
  name: chat
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ahoy-chat
  namespace: chat
spec:
  selector:
    matchLabels:
      app: ahoy-chat
  template:
    metadata:
      labels:
        app: ahoy-chat
    spec:
      containers:
      - name: chat
        image: ttl.sh/ahmae1jeiyapiemeiguobaf6ue8ju0vae4hoh9ji6gieng4uoc9ael3iewai5joh:1h
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: REDIS_URL
            value: redis://redis:6379
          - name: PORT
            value: "8080"
        ports:
        - containerPort: 8080
          name: chat
---
apiVersion: v1
kind: Service
metadata:
  name: ahoy-chat
  namespace: chat
  annotations:
    external-dns.alpha.kubernetes.io/hostname: chat.ahoy.wiseflow.io
spec:
  selector:
    app: ahoy-chat
  ports:
  - protocol: TCP
    port: 80
    targetPort: chat
  type: LoadBalancer
---
# Persistent volume claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: chat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp3
---
# Redis deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.0.4-alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
          resources:
            requests:
              cpu: "3"
              memory: 1Gi
            limits:
              cpu: "3"
              memory: 1Gi
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc
---
# Redis loadbalancer service
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: chat
  annotations:
    external-dns.alpha.kubernetes.io/hostname: redis.ahoy.wiseflow.io
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: redis

